import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import * as ReactDOM from "react-dom/client";
import * as React from "react";
import Button from "@mui/material/Button";
import { TextField } from '@mui/material';
import NumberFormat from 'react-number-format';
import Link from 'next/link';

const Home: NextPage = () => {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Link href='money'>
            <Button variant="contained"> Olá Mundo</Button>
        </Link>

       
      

      </main>
    </div>
  )
}

export default Home
